version: "3"
services:
  myapp:
    image: stackupiss/northwind-app:v1
    ports:
      - "8080:3000"
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - mynet
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - mydb-data:/var/lib/mysql
    networks:
      - mynet

networks:
  mynet:

volumes:
  mydb-data:
