apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

commonLabels:
  env: prd

namespace: prd-ns

namePrefix: prd-
nameSuffix: -team1

replicas:
  - name: dov-deploy
    count: 3

images:
  - name: chkmunnlee/dov-bear
    newTag: v4
