---
apiVersion: v1
kind: Namespace
metadata:
  name: db-ns
labels:
  app: db
---
# Persistent volume claim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db-ns
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: db-ns
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      name: db-po
  template:
    metadata:
      name: db-po
      labels:
        app: db
        name: db-po
    spec:
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
        - name: db-container
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeit
          ports:
            - name: db-port
              containerPort: 3306
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/mysql
