---
apiVersion: v1
kind: ConfigMap
metadata:
  name: htmls
  labels:
    app: webserver

data:
  index.html: |
    <html>
      <head>
        <title>Welcome to nginx!</title>
      </head>
      <body>
        <h1>Hello World!</h1>
      </body>
    </html>
  about.html: |
    <html>
      <head>
        <title>About nginx!</title>
      </head>
      <body>
        <h1>About World!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  volumes:
    - name: html-vol
      configMap:
        name: htmls
    - name: tmp-vol
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx:1.25
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-vol
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: tmp-vol
          mountPath: /tmp
