apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    dept: engineering
    env: uat
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: dov-bear
  namespace: myns
spec:
  containers:
    - name: my-container
      image: chukmunnlee/dov-bear:v4
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: INSTANCE_NAME
          value: "my-pod"
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
